### ISSUE TITLE
Lambda ENV variable for SUBREDDITS_TO_FOLLOW is not being set when deploying through CFN

### ISSUE THREAD

**Issue by michelangelo17** [aws-solutions/discovering-hot-topics-using-machine-learning#69]
**Describe the bug**
Lambda ENV variable for SUBREDDITS_TO_FOLLOW is not being set corretly when deploying through CFN, when deploying from the solution library, you then have to manually go to the lambda function and change the ENV variable to get it to work. 

**To Reproduce**
Steps to reproduce the behavior.
Attempt to deploy Reddit portion of solution, issue occurs every time.

**Expected behavior**
The ENV variable should be set by the CFN parameter SubRedditsToFollow.

**Please complete the following information about the solution:**
- [x] Version: v2.0.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0122) - Discovering Hot Topics using Machine Learning. Version v1.1.0".

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? No.
- [x] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [x] Were there any errors in the CloudWatch Logs? No.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
Will be adding a pull request to fix soon.

**Comment by knihit** [comment]
@michelangelo17 thanks for reaching out. I will try and reproduce the issue as well.

**Comment by knihit** [comment]
@michelangelo17 if its ok to share, can you please let us know the CFN parameter you set when deploying for reddit portion.

**Comment by michelangelo17** [comment]
Cfn parameter: SubRedditsToFollow

This parameter doesn't get passed to lambda for the ENV variable SUBREDDITS_TO_FOLLOW

**Comment by knihit** [comment]
@michelangelo17 , if its ok can you share the value of the Cfn Parameter. I just deployed the stack with the following value `r/aws,r/MachineLearning` and I can see it in the environment variables for the lambda. I would like to check if your value has any special characters that is causing the issue.

**Comment by michelangelo17** [comment]
r/foodsecurity,r/ZeroWaste

The issue is that it won't pass down the values, it appears the ENV variable is hardcoded to the ones you used

**Comment by knihit** [comment]
@michelangelo17 acknowledging the issue. This line https://github.com/aws-solutions/discovering-hot-topics-using-machine-learning/blob/main/source/lib/ingestion/ingestion-construct.ts#L173 is missing the parameter for subreddits. I will add it to the backlog and see if we can do a quick release to fix it. As a workaround, as you suggested, post deployment the lambda environment variables need to be edited for subreddits.
